### ISSUE TITLE
"Most simple use case" didn't work

### ISSUE THREAD

**Issue by icemagno** [intarsys/smartcard-io#10]
```
		try {
		
			IPCSCContext context = PCSCContextFactory.get().establishContext();
			List<IPCSCCardReader> readers = context.listReaders();	        
			for (IPCSCCardReader reader : readers) {
				System.out.println( reader.getName() );
			}
		}catch (Exception e) {
			e.printStackTrace();
		}
```

```Caused by: java.lang.NoClassDefFoundError: de/intarsys/tools/system/SystemTools```

**Comment by eheck-is** [comment]
You're missing a dependency, "intarsys-tools-runtime" specifically (or "isrt" if you're using the outdated older version), maybe others. If you're using the Maven package, Maven (or Gradle or whatever you're using) should pull the correct dependencies. If not you have to set up the dependencies yourself. If you do have "intarsys-tools-runtime" in the classpath, please post the complete stack trace.

**Comment by icemagno** [comment]
Well.. sorry for this, but I came from google serach and know nothing about this project. 
In short, for all people like me, I just follow the "USAGE" instructions on main page.

Didn't know the dependencies  gradle file must be read too to know what I must do before this step.

What about put "Dependencies" before "Usage" ?

**Comment by eheck-is** [comment]
The "Build" section says: "is provided as a [...] Gradle project". I don't want to replicate Gradle documentation on how to use a Gradle project here. But glad that your issue has been resolved.
