### ISSUE TITLE
InternalError when transmitting a control command with empty command data

### ISSUE THREAD

**Issue by Baco9** [intarsys/smartcard-io#4]
I'm getting `InternalError: "can not create Pointer"` when transmitting a control command with empty command data. The calling code looks something like this:

``` java
final int GET_FEATURES = 0x42000D48;
card.transmitControlCommand(GET_FEATURES, new byte[0]);
```

PCSCConnection will try to allocate a zero-bytes memory buffer, which results in com.sun.jna.Memory throwing an IllegalArgumentException, which results in the InternalError being thrown.

I'm not sure if using an empty command data array is normal practice, but the code is from a library I'm using (Commons eID Project), so I don't really have much control over it.

Stack:

```
Memory.<init>(long) line: 87
GeneratedConstructorAccessor70.newInstance(Object[]) line: not available
DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45
Constructor<T>.newInstance(Object...) line: 408
JnaNativeInterface.createMemory(int) line: not available
JnaNativeInterface.allocate(int) line: not available
NativeBuffer.<init>(int) line: not available
PCSCConnection.control(int, byte[], int, int, int) line: 102
StandardCardConnection.basicControl(int, byte[], int, int, int) line: 125
StandardCardConnection(CommonCardConnection).control(int, byte[], int, int, int) line: 328
CardImpl.transmitControlCommand(int, byte[]) line: 137
CCID.<init>(Card, Logger) line: 98
BeIDCard.getCCID() line: 1511
BeIDCard.sign(byte[], BeIDDigest, FileType, boolean) line: 502
```

I'm using Java 1.8.0_31 on OS X 10.10.2.

**Comment by mtraut** [comment]
Thx for the feedback, i will have a look at this soon...

Am 14.02.2015 17:36 schrieb Baco9 <notifications@github.com>:

I'm getting InternalError: "can not create Pointer" when transmitting a control command with empty command data. The calling code looks something like this:

final int GET_FEATURES = 0x42000D48;
card.transmitControlCommand(GET_FEATURES, new byte[0]);

PCSCConnection will try to allocate a zero-bytes memory buffer, which results in com.sun.jna.Memory throwing an IllegalArgumentException, which results in the InternalError being thrown.

I'm not sure if using an empty command data array is normal practice, but the code is from a library I'm using (Commons eID Project), so I don't really have much control over it.

Stack:

Memory.<init>(long) line: 87
GeneratedConstructorAccessor70.newInstance(Object[]) line: not available
DelegatingConstructorAccessorImpl.newInstance(Object[]) line: 45
Constructor<T>.newInstance(Object...) line: 408
JnaNativeInterface.createMemory(int) line: not available
JnaNativeInterface.allocate(int) line: not available
NativeBuffer.<init>(int) line: not available
PCSCConnection.control(int, byte[], int, int, int) line: 102
StandardCardConnection.basicControl(int, byte[], int, int, int) line: 125
StandardCardConnection(CommonCardConnection).control(int, byte[], int, int, int) line: 328
CardImpl.transmitControlCommand(int, byte[]) line: 137
CCID.<init>(Card, Logger) line: 98
BeIDCard.getCCID() line: 1511
BeIDCard.sign(byte[], BeIDDigest, FileType, boolean) line: 502


I'm using Java 1.8.0_31 on OS X 10.10.2.

-

**Comment by martinpaljak** [comment]
This is normal behaviour. You might want to look at [jnasmartcardio](https://github.com/jnasmartcardio/jnasmartcardio) meanwhile, it also provides a working alternative javax.smartcardio implementation on OSX as is currently without blocking issues, as you can verify with [apdu4j](https://github.com/martinpaljak/apdu4j)

**Comment by Baco9** [comment]
Thanks for the suggestion @martinpaljak.
The problem is that the library I use (Commons eID Project) assumes that `CardTerminals.list()` returns the same CardTerminal objects on subsequent calls, but jnasmartcardio returns new ones every time. Maybe I should just make a patch for the Commons eID Project...

**Comment by martinpaljak** [comment]
Interesting observation. Quick glance over smartcardio api does not suggest that this should be the expected behaviour. Do you have a link to the relevant source lines in the belgian project ?

**Comment by mtraut** [comment]
@Baco9 i've committed a fix for the problem - unfortunately i can not test from my site here. We never tested an empty buffer (i must admit we used "null" - which works by workaround). So now it should be fine... but it would be great if you give feedback if you give it a try.

To my great surprise the last release is already about 2 years. I will try to fix this, too in the upcoming weeks.

@martinpaljak you're right, there's nothing in the docs that requires identity - but it eases life considerably and much of our own code depends onthis behavior.

**Comment by Baco9** [comment]
Thanks @mtraut, it seems to be working.
I'm getting a different error now, but it seems unrelated at first sight. I'll look into that later today.

To released jar file did not include the de.intarsys.security.smartcard.smartcardio package by the way, so I had to compile it myself.

@martinpaljak take a look at [CardAndTerminalManager.java](https://code.google.com/p/commons-eid/source/browse/commons-eid-client/src/main/java/be/fedict/commons/eid/client/CardAndTerminalManager.java?spec=svn4d67836a35eaf072ff8df33047b63fd3408ee59f&r=4d67836a35eaf072ff8df33047b63fd3408ee59f#465), lines 467-500. The CardTerminals are stored in a Set, and compared using object identity, triggering terminalsAttached/terminalsDetached notifications on every iteration.
I already reported the [issue](https://code.google.com/p/commons-eid/issues/detail?id=5).
