### ISSUE TITLE
cannot find symbol import de.intarsys.security.smartcard.pcsc.PCSCStatusMonitor.IStatusListener;

### ISSUE THREAD

**Issue by LudovicRousseau** [intarsys/smartcard-io#6]
My source code file `Foo.java`:
```
import de.intarsys.security.smartcard.pcsc.PCSCStatusMonitor.IStatusListener;
import de.intarsys.security.smartcard.pcsc.nativec._IPCSC;

public class Foo {
}
```

If I compile it with no special argument:
```
$ javac Foo.java 
Foo.java:1: error: package de.intarsys.security.smartcard.pcsc.PCSCStatusMonitor does not exist
import de.intarsys.security.smartcard.pcsc.PCSCStatusMonitor.IStatusListener;
                                                            ^
Foo.java:2: error: package de.intarsys.security.smartcard.pcsc.nativec does not exist
import de.intarsys.security.smartcard.pcsc.nativec._IPCSC;
                                                  ^
2 errors
```
The error is expected.

No I use the provided is-smartcard-io.jar
```
$ javac -classpath is-smartcard-io.jar Foo.java 
Foo.java:1: error: cannot find symbol
import de.intarsys.security.smartcard.pcsc.PCSCStatusMonitor.IStatusListener;
                                                            ^
  symbol:   class IStatusListener
  location: class PCSCStatusMonitor
1 error
```

What is the problem with `IStatusListener`?
It may be a stupid mistake from my side. I am not a Java expert or even user.

My Java version:
```
$ java -version
openjdk version "14-ea" 2020-03-17
OpenJDK Runtime Environment (build 14-ea+36-Debian-2)
OpenJDK 64-Bit Server VM (build 14-ea+36-Debian-2, mixed mode, sharing)
```

**Comment by LudovicRousseau** [comment]
This import is used in the Connect.java sample code at https://github.com/intarsys/smartcard-io/blob/master/examples/de/intarsys/security/smartcard/pcsc/Connect.java#L5

**Comment by mtraut** [comment]
Hello Ludovic,

Elfi will support you on this tomorrow.

**Comment by eheck-is** [comment]
Hi Ludovic, the is-smartcard-io.jar file is indeed broken. Thanks for noticing. I'll rebuild and replace the file.
If you don't want to wait, you can build the project from source yourself. The code uses the javax annotation API, however, and will not build (and run) with a vanilla JDK 14. You'd have to get javax.annotation-api.jar from somewhere (e.g. Maven Central) or use Java 8

**Comment by eheck-is** [comment]
I've replaced the file. You will still need javax.annotation-api.jar to run with JDK 14.

**Comment by LudovicRousseau** [comment]
Fixed. Thanks.
