### ISSUE TITLE
Maven repo?

### ISSUE THREAD

**Issue by richardSch** [intarsys/smartcard-io#8]
Is this available in a Maven repository?
If not, would it be possible to add the following to build.gradle so I can use Gradle Source Dependency to include this library?

`
allprojects {
    group = 'de.intarsys.security'
    version = '1.0'
}
`

**Comment by mtraut** [comment]
No, not available in maven et. al. - you need to build from source.

I do not know what exactly is your problem or intent, so i just added some gradle meta information that roughly matches out internal coordinates. 

Hope this helps - if not, describe your problem or intent.

**Comment by CamperSamu** [comment]
this should be reopened in favor of a Jitpack repo
